baseURL = 'https://dev.viktormaruna.com/'
languageCode = 'en-us'
title = 'Viktor Maruna â€” Cloud, Data & AI'
enableRobotsTXT = false

theme = 'vm'

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = ""

# RSS Feed configuration
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Cloud, Data & AI"

  [params.author]
    name = "Viktor Maruna"
    url = "https://viktormaruna.com"
    linkedin = "https://linkedin.com/in/viktormaruna/"
    github = "https://github.com/viktormaruna"

  [params.giscus]
    repo = "viktormaruna/viktormaruna.github.io-dev"
    repoId = "R_kgDOPMfe-Q"
    category = "General"
    categoryId = "DIC_kwDOPMfe-c4Ct-5F"

[markup.tableOfContents]
  startLevel = 2
  endLevel   = 4
  ordered    = false

[markup.highlight]
  codeFences  = true
  guessSyntax = true
  noClasses   = false

[imaging]
  quality = 85
  resampleFilter = "Lanczos"

  [imaging.exif]
    disableDate    = true
    disableLatLong = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'