baseURL = 'https://dev.viktormaruna.com/'
languageCode = 'en-us'
title = 'Viktor Maruna â€” Cloud, Data & AI'

theme = 'vm'

paginate = 10

# Enable tags taxonomy
[taxonomies]
  tag = "tags"

# Enable tag and category pages
# RSS Feed configuration
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Cloud, Data & AI"
  
  [params.giscus]
    enable = true
    repo = "viktormaruna/viktormaruna.github.io-dev"
    repoId = "R_kgDOPMfe-Q"
    category = "General"
    categoryId = "DIC_kwDOPMfe-c4Ct-5F"

[markup.tableOfContents]
  startLevel = 2
  endLevel   = 4
  ordered    = false

[markup.highlight]
  codeFences  = true
  guessSyntax = true
  noClasses   = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'